source 'https://rubygems.org'

gem 'selenium-webdriver'
gem 'cucumber', '2.4.0'
gem 'test-unit'
gem 'rake'
gem 'appium_lib'
gem 'appium_console'
gem 'allure-cucumber'
gem 'yard-cucumber'
gem 'redcarpet'